### ISSUE TITLE
Add an nginx container to the AI Agent Host with Let's Encrypt and Certbot

### ISSUE THREAD

**Issue by BouarfaMahi** [BouarfaMahi/AI-Agent-Host#1]
Running nginx  provide several benefits. Here are a few examples:

- Reverse Proxy: Nginx can act as a reverse proxy to expose multiple services on the same port, so you could use it to expose Code-server, Grafana, and QuestDB on a single port, such as 80 or 443. This can make it easier to access these services from a web browser without having to remember multiple ports.

- SSL/TLS Termination: Nginx can also be used to terminate SSL/TLS connections and then pass decrypted traffic to your application containers. This can be particularly useful if you want to secure your application with SSL/TLS.

- Load Balancing: If you have multiple instances of your application containers, Nginx can be used as a load balancer to distribute incoming traffic across them. This can help to improve performance and ensure that your application remains available even if one of the containers goes down.

- Caching: Nginx can also be used as a caching layer to improve the performance of your application. By caching frequently accessed resources, you can reduce the load on your application containers and improve response-time.

Overall, adding an nginx container to your Docker Compose setup that includes QuestDB, Code-server, and Grafana can provide several benefits. However, whether or not it makes sense to do so depends on the specific requirements of your application and the goals you're trying to achieve.

For each Microserver  allow HTTPS connection to Web Applications:

https://vscode.domain.tld
https://questdb.domain.tld
https://grafana.domain.tld

and use this [Nginx configuration](https://github.com/BouarfaMahi/AI-Agent-Farm/tree/master/doc/it-admin/nginx/microserver) file:

**Comment by BouarfaMahi** [comment]
add label

**Comment by isnoor** [comment]
I don't know why blocked on upwork, I hope it is not spam
